name: Health check

on:
  schedule:
    - cron: 10 * * * *
  # push:
    # branches:
      # - master

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check deployed app URL is working
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://holy-dew-9210.fly.dev/
